### ISSUE TITLE
Make FindMKL.cmake compliant with Intel documentation

### ISSUE THREAD

**Issue by juliohm** [hanjianwei/cmake-modules#1]
According to [Intel documentation](https://software.intel.com/en-us/node/438544), the root directory for Intel MKL is stored in `MKLROOT` environment variable on Linux. The module should use this variable as in `set(MKLROOT $ENV{MKLROOT})` and not assume `/opt/intel`.

We also need support for other architectures, specially `intel64`.

**Comment by juliohm** [comment]
@hanjianwei, any comments?

**Comment by hanjianwei** [comment]
@juliohm Sorry for my late reply!

I didn't use MKL for a long time. I will see the document. Can you send a pull request?

Thanks

**Comment by juliohm** [comment]
@hanjianwei, right now I'm not using it either, the change I mentioned is straightforward:

Replace https://github.com/hanjianwei/cmake-modules/blob/master/FindMKL.cmake#L20-L21

by

``` cmake
set(MKL_ROOT $ENV{MKLROOT})
```

Intel MKL is very disorganized, we should try follow their documentation whenever possible.
